### ISSUE TITLE
Get permission service: clean "can_request_help" usage

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#1004]
## Motivations

The current spec of the service does not really work how the "can_request_help" is designed. So let's fix it.

## Subtasks
- [x] in `computed` and all `granted_via_*`, `can_request_help_to` is aggregate of several groups, so return an array of the (id, is_all_users_group, name) tuple. This should be `[]` is there is no such groups.
- [x] in `granted`, the `can_request_help_to` is unique to keep (id, is_all_users_group, name). `can_request_help_to` should be null if there is no value set.
- [x] In both cases, if a group is not visible by the current user, the `name` should not be given, but the `id` or `is_all_users_group` should be given in any case.
