### ISSUE TITLE
getAnswer:

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#1016]
## Motivations

Currently, the [answerGet](https://franceioi-algorea.s3.eu-west-3.amazonaws.com/spec/v1.13.2.html#tag/answers/operation/answerGet) service return the response for the user who owns it and the observers. However, we would like to be able to show the answers to anybody who can view the forum thread of a user (a participant). 

## Subtasks
- [ ] anybody who can read a forum thread must be able to call `answerGet` on an answer corresponding to this participant and this item. So, I think you have to add to allowed cases of `answerGet`: 
  - [ ] when can_watch>=answer permission on the item even without can_watch_member on the participant
  - [ ] a user who are part of the group the participant has requested help to, AND the correspond thread is either open or closed for less than 2 weeks, AND the user has validated the item

**Comment by smadbe** [comment]
I see in my notes what we decided (long ago) to do it differently (to store the answer in dyndb instead).
