### ISSUE TITLE
Update group: handle approval requirement changes

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#1039]
## Motivations

The current update group service lets the user change the approval as he wants, but in practice, you should not be able to change the rules while some member has approved them already.

## Subtasks
- [ ] `require_lock_membership_approval_until` should be nullable (it should be able to re-set this value to null when not null)
- [ ] if there is at least one participant (user ou team) in the group and one of the approval rule is strengthened:
  - [ ] if `approval_change_action` is not given, fail (403?)
  - [ ] if `approval_change_action` is "empty", remove all the participant from group 
    - [ ] update `membership_changes` table as well !
  - [ ] if  `approval_change_action` is "reinvite", remove all the participant from group and invite them to join the group
- [ ] if no approval rule is strengthened, `approval_change_action` **must** not be given
- [ ] `require_lock_membership_approval_until` is strengthened if the new value is >NOW and either:
  - [ ] the previous value was null, or
  - [ ] the previous value < the new value
- [ ] `require_watch_approval` is strengthened if was `false` and becomes `true`
- [ ] `require_personal_info_access_approval`  is strengthened if was `none` and become s`read` or `edit`, or if was `read` and becomes `edit`

**Comment by smadbe** [comment]
This `group_membership_changes` has become just a log. So we could use `removed` (as the membership has been removed by a manager) but if the goal is to be able to understand why a member is not member anymore probably an entry such as `removed_due_to_approval_change` may help.

**Comment by GeoffreyHuck** [comment]
What happens if the group in question have subgroups and a field is strengthtened?
- Do we remove the subgroups?
- Do we remove the users in the subgroups?

**Comment by smadbe** [comment]
> What happens if the group in question have subgroups and a field is strengthtened?
> 
>     * Do we remove the subgroups?

No

>     * Do we remove the users in the subgroups?

No

Subgroups would be to difficult to manager, for instance if you add the group in another parent group, you would get a set of new approval rules, you would have to re-invite everybody, ...

**Comment by smadbe** [comment]
I have added 3 lines related with join/leave requests that may also be dropped if rules change (as the user approves the rules when creating the request)
