### ISSUE TITLE
Adapt invitation service to current needs

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#1056]
## Motivations

The group invitation service is one of the oldest service and many things have changed around it. In addition, to get "approvals" that the user has to approval, he needs to get them (and he is not allowed to get the group info to get them).

## Subtasks

Update the `GET /current-user/group-invitations` service so that:
- [x] only return actual invitation the user has received (that he has not approved yet, which has not been removed, ...), no more join request things
- [x] so no need for the "action" in the output anymore
- [x] the `group` in output should include the 3 approval field values
- [x] `inviting_user` should not be `nullable` anymore I assume
- [x] I think `within_weeks` is not useful anymore... so if it is easier to remove it, remove it (otherwise, you can leave it as it is)
