### ISSUE TITLE
Cleaning up "contests" services

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#1169]
## Motivations

A few services are under the "contest" category [in the doc](https://franceioi-algorea.s3.eu-west-3.amazonaws.com/spec/v2.22.2.html#tag/contests) and have a "contests" in their url. 
However, this is about items which have explicit-entry and have a duration... but we may have contests which do not match these and mainly non-contest matching these properties. So I would prefer we get rid of the "contests" name.

## Subtasks

- [ ] For setting/listing additional time, we could just use "items" in the url instead of "contests"
- [ ] "Get a group by name " is marked as transitional, it can now be removed
- [ ] "List administered contests " is currently unused, I would move it under "/items/time-limited" or "/items/time-limited/managed"
- [ ] "List additional times on a contest " should mention the unit of `*additional_time` fields
