### ISSUE TITLE
Forum: initial setup

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#855]
## Motivations

To support the new "forum" feature (i.e. discussion thread related to participant-item pair), we need a few new tables and services This issue is a prerequisites for the next ones. Technical details are discussed in the [dev doc](https://france-ioi.github.io/algorea-devdoc/forum/).

## Subtasks

- [ ] drop the existing `messages`, `threads` and `user_thread` tables, they will not be used or a bit differently
- [ ] create a new `threads` table with as attributes:
  * participant_id, item_id (PK) 
  * status (enum : `waiting_for_participant`, `waiting_for_trainer`, `closed`. Any name fancier than "waiting_for_" is welcome... for instance including "open" (to be discussed first))
  * latest_status_update_at (datetime)
  * helper_group (FK to group.id)
  * latest_message_at (datetime)
- [ ] new permission (in `permissions_granted` only?): `can_request_help_to` which takes a `group` (FK) as argument
  * NULL can probably be interpreted as "to nobody" (= no perm)
- [ ] add a new propagation rule `help_request_propagation` on `items_items`
  - [ ] the `PUT /item/:id` service should apply a similar rule as the edit/watch/grant_view propagation for the default value set to `help_request_propagation`, i.e. set the highest possible value depending on user's perm
- [ ] initial service ; TODO

- [ ] Make sure no problem occurs with FK if a group if deleted:
  - [ ]* `permissions_granted.can_request_help_to` should probably be set back to NULL 
  - [ ] `threads.helper_group` should  probably be set to the all users group (it is a config parameter)

**Comment by smadbe** [comment]
Modified many times, now split into several issues
