### ISSUE TITLE
Forum: new permission and propagation

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#883]
## Motivations

To support the new "forum" feature (i.e. discussion thread related to participant-item pair), we need a few new tables and services This issue is a prerequisites for the next ones. Technical aspects are discussed in the [dev doc](https://france-ioi.github.io/algorea-devdoc/forum/).

This issue only focus on permissions.

## Subtasks

- [x] new permission (in `permissions_granted` only?): `can_request_help_to` which takes a `group` (FK) as argument
  * NULL can probably be interpreted as "to nobody" (= no perm)
- [x] add a new propagation rule `help_request_propagation` on `items_items`
  - [x] the `PUT /item/:id` service should apply a similar rule as the edit/watch/grant_view propagation for the default value set to `help_request_propagation`, i.e. set the highest possible value depending on user's perm
- the propagation mechanism should not be changed
- [x] Make sure no problem occurs with FK if a group if deleted: `permissions_granted.can_request_help_to` should be set back to NULL if the related group is deleted

- Adding the new permissions to the services returning/updated them will be done later.
