### ISSUE TITLE
Forum: initial service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#884]
## Motivations

To support the new "forum" feature (i.e. discussion thread related to participant-item pair), we need a few new tables and services This issue is a prerequisites for the next ones. Technical aspects are discussed in the [dev doc](https://france-ioi.github.io/algorea-devdoc/forum/).

## Subtasks

- [x] drop the existing `messages`, `threads` and `user_thread` tables, they will not be used or a bit differently
- [x] create a new `threads` table with as attributes:
  * participant_id, item_id (PK) 
  * status (enum : `waiting_for_participant`, `waiting_for_trainer`, `closed`. Any name fancier than "waiting_for_" is welcome... for instance including "open" (to be discussed first))
  * ~~latest_status_update_at (datetime, not null, default to now)~~
  * helper_group_id (FK to group.id, not null)
  * latest_update_at (datetime, not null, default to now). Comment "Last time a message was posted or the status was updated"
  * message_count (not null number, default to '0'). Comment "Approximation of the number of message sent on the thread."

- [x] Make sure no problem occurs with FK if a group if deleted: `threads.helper_group` should  probably be set to the all users group (it is a config parameter) if the group is deleted

- [x] initial service on `GET /items/:item_id/participant/:participant_id/thread` to retrieve thread information
  - outputs
     - participant_id
     - item_id
     - status, including a status "not_started" is the thread does not exist (no entry)
  
  - Validations
    * one of these conditions matches:
       * the current-user is the thread participant and allowed to `can_view>=content` the item
       * have `can_watch>=answer` permission on the item
       * match all rules:
          * the current-user is descendant of thread `helper_group`
          * the thread is either open (=`waiting_for_participant` or `waiting_for_trainer`), or closed for less than 2 weeks
          * the current-user has validated the item
