### ISSUE TITLE
Forum: add authorization token in thread service

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#890]
## Motivations

As the actual forum content (messages, events) are handled in a different service, we need to provide this service with a way to validate the access the user is requesting on the thread.

The token is not related at all with the task token (hint token, answer token, ...) which are used to communicate with tasks, but similar mechanism may be used. Basically, the idea is to provide a JWT which contain a set of key-value and to sign these with the backend asymmetric private key so that it can be verified by any other service.

## Subtasks

- [ ] In the GET thread service which has been developed in #884, add a "token" attribute
- [ ] The token should contain, in its payload: 
   - `item_id`
   - `participant_id`
   - `user_id`: the current user id
   - `is_mine` (bool) : whether the thread is for the current-user... for now just `user_id == participant_id`
   - `can_watch` (bool): whether the current user can watch the participant on this item (i.e. `can_watch>=answer` permission on the item AND `can_watch_members` on the participant)
   - `can_write` (bool): whether the user can post new content on the thread ([writing in a thread](https://france-ioi.github.io/algorea-devdoc/forum/forum-perm/#writing-in-a-thread))
- [ ] The token should be signed by the backend
