### ISSUE TITLE
Update services for the recent forum permission

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaBackend#968]
## Motivations
Recently, we have added a new permission for the forum. This new perm should be added in the services related with permission management.

## Subtasks

- [x] add `can_request_help_to` to `grantedPermissionsView`
- [x] add `can_request_help_to` to `permissionsView` in `granted`. The value should be either null (if not the perm), either a tuple containing the `id`, `name` only if it is visible to the current-user, either a `is_all_users_group` boolean to indicate whether the group is the "all-users" group.
- [x] add  `can_request_help_to` to `updatePermissions`: [as written in the doc](https://france-ioi.github.io/algorea-devdoc/forum/forum-perm/), the group must visible to both the giver and the received. In order to be able to set the "all group" group, the value should be a tuple with either `id` or `is_all_users_group: true` (not both) (or at root `can_request_help_to_all_users:bool`|`can_request_help_to:number` ?)
- [x] add `request_help_propagation` to `itemCreate`
- [x] add `request_help_propagation` to `itemUpdate`
- [x] add `request_help_propagation` to `itemChildrenView`

**Comment by GeoffreyHuck** [comment]
Note: Found out it has already been done for `itemUpdate` here: https://github.com/France-ioi/AlgoreaBackend/commit/d64a5abbc20c034245d23160233c11afab38ef70 (but not for `itemCreate` yet)
